version: "3.8"

services:
  app:
    image: node:16
    depends_on:
      - mariadb
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app

    env_file:
      - ./.env
    environment:
      MYSQL_HOST: $DB_HOST
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DB: $DB_NAME

  mariadb:
    image: mariadb
    env_file:
      - ./.env
    ports:
      - $DB_PORT:$DOCKER_DB_PORT
    volumes:
      - db:/var/lib/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME

volumes:
  db: null
