version: "3.8"

services:
    app:
        image: node:16-alphine
        command: sh -c "yarn install && yarn run dev"
        ports:
          - 3000:3000
        working_dir: /app
        volumes: 
            - ./:/app
    mariadb:
      image: mariadb
      env_file: ./.env
      environment: 
        MARIADB_ROOT_PASSWORD: $MARIA





                
